### ISSUE TITLE
licence 

### ISSUE THREAD

**Issue by maggick** [tupperVim/tuppervim.github.io#10]
J'ai reçu une demande sur IRC pour que l'on précise la licence du contenu du site :

     maggick: tu pourrais préciser la licence du contenu du site stp ? (ping aussi kaze) 

Personnellement je pensais à une WTFPL (ou LPRAB).

Il faut voir avec le logo qui est sous GPL (cf. [wikipedia](http://fr.wikipedia.org/wiki/Vim#/media/File:Vimlogo.svg)).

Des avis ? Suggestions ?

**Comment by maggick** [comment]
v45h_ | maggick: Pourquoi pas une bière license ?                                                                                       
    v45h_ | Ça a l'avantage d'avoir des bières gratuites :-D

**Comment by bnjbvr** [comment]
Je propose d'adapter librement la license de fuckitjs:

> Copyright (C) 2012, Matt Diamond
> 
> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, pulverize, distribute, synergize, compost, defenestrate, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
> 
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
> 
> If the Author of the Software (the "Author") needs a place to crash and you have a sofa available, you should maybe give the Author a break and let him sleep on your couch.
> 
> If you are caught in a dire situation wherein you only have enough time to save one person out of a group, and the Author is a member of that group, you must save the Author.
>
>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO BLAH BLAH BLAH ISN'T IT FUNNY HOW UPPER-CASE MAKES IT SOUND LIKE THE LICENSE IS ANGRY AND SHOUTING AT YOU.

https://github.com/mattdiamond/fuckitjs

**Comment by fabi1cazenave** [comment]
Perso j’aime bien la WTFPL parce que c’est la seule licence dont je comprends tous les mots. De plus, elle correspond bien à l’esprit du canal de discussion (classe, distinction, toussa…).

Si le logo est sous GPL il faudra faire une exception de licence, ce qui fait très classe également. Que du positif.

La “Beer License” est sympa aussi mais je crois qu’on la respecte déjà naturellement sans qu’il soit besoin de la préciser. :-)

**Comment by maggick** [comment]
plus sérieusement, github a créé http://choosealicense.com/ pour aider à choisir un licence (à garder pour vos futur projets).

**Comment by maggick** [comment]
merged par @fabi1cazenave
