### ISSUE TITLE
Création d'un nouveau logo

### ISSUE THREAD

**Issue by maggick** [tupperVim/tuppervim.github.io#124]
comme vous le savez sûrement, l’anniversaire des 5 ans de nos réunions arrive.
Pour l'occasion nous souhaiterions réaliser des stickers en édition
limitée ainsi que des tshirts.

Il est envisageable de changer complètement le logo, de le transformer
ou de le reprendre.

Si vous vous sentez l'âme de graphisme n'hésitez pas à nous proposer
des idées de stickers, de logo ou autre.
N'hésitez pas a soumettre un maximum d'idée, promis personne ne se moquera.

Si vous avez des idées de logo ou de stickers, de stickers édition limitée 5ans voir de desing pour t-shirt, mettez les ici !

**Comment by guyzmo** [comment]
moi j'ai une idée mais pas les compétences pour la réaliser: utiliser un tupperware ou un capuchon de tupperware vert derrière la typo de vim, à la place du losange vert.

Simple. Efficace. Puissant. ☺

**Comment by kevlarcade** [comment]
une flamme représentant une bougie sur le i de vim mais j'ai pas les compétence non plus.

**Comment by maggick** [comment]
j'aime beaucoup la proposition de @nojhan ça rendra super bien sur un tshirt

**Comment by romainl** [comment]
@kevlarcade un peu comme ça ?

![01](https://cloud.githubusercontent.com/assets/344335/23633816/8567a8c6-02c7-11e7-80d7-3be3dd630751.png)

**Comment by maggick** [comment]
classe aussi

**Comment by guyzmo** [comment]
(et `ZZ` dans le dos ? ☺)

**Comment by maggick** [comment]
Que pensez vous de ce design : http://nicolac76.free.fr/Nicolas.jpg
Il faut être assez réactif, les 5 sont dans un mois.

**Comment by romainl** [comment]
@maggick, le logo est OK mais le t-shirt est KO.

**Comment by alkino** [comment]
Bon on prends le logo de @nojhan alors ?
Pour le t-shirt on va passer sur : http://www.logovision.be/16814-thickbox/t-shirt-full-cut-fruit-of-the-loom.jpg

**Comment by romainl** [comment]
@alkino je valide et te dois 15€.

**Comment by maggick** [comment]
Un petit sondage pour le choix du logo [https://framadate.org/9f5roQxBoOFKGPJJ]
On adaptera la design du tshirt en fonction

**Comment by alkino** [comment]
Bon ba @romainl t'as plus qu'à nous filer ton logo en svg et en png. Et de faire une petite PR pour remplacer l'ancien. ;)

Pour les t-shirt : http://tuppervim.org/t_shirt.html

**Comment by romainl** [comment]
@alkino j'ai déjà tout filé à @maggick ;-)

**Comment by maggick** [comment]
yep

**Comment by alkino** [comment]
Et donc... ? @maggick

**Comment by maggick** [comment]
le logo n'est pas visible avec le fond actuel

**Comment by romainl** [comment]
:%s/#000000/#ffffff/g
