### ISSUE TITLE
TupperVim Grenobloise / Lyonnaise

### ISSUE THREAD

**Issue by JulioJu** [tupperVim/tuppervim.github.io#175]
Bonjour,

J'ouvre une « issue », because ça fait longtemps que y'a pas eu de TupperVim à Grenoble ou/et Lyon :cry: :sob: :cry:.

C'est donc une véritalbe « issue » :smile:

See you ;-)

**Comment by Delapouite** [comment]
Allez, on coupe la poire en 2: prochaine édition à Bourgoin Jallieu

**Comment by fflorent** [comment]
@fabi1cazenave j'attends juste tes disponibilités. Après si on veut le faire à l'ENS durant le mois de juin, il faut une réponse rapide :)

Florent

**Comment by JulioJu** [comment]
Trop géant :-)

**Comment by fabi1cazenave** [comment]
Wopopop j’avions pô vu ! Mais ouais, à fond pour un tupperVim à Lyon ou Grenoble. Je suis dispo pendant la semaine du 18 au 22 juin.

**Comment by fabi1cazenave** [comment]
https://twitter.com/tupperVim/status/1004686969153245184

**Comment by JulioJu** [comment]
Trop cool !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! :heart: :heart: . Je commençais à avoir des tremblements because ça me manquait… C'était grave quoi… :rofl: ;-)

J'espère que ce ne serait pas le 21, parce qu'il est possible que je ne puisse pas :sob: .

**Comment by JulioJu** [comment]
@fabi1cazenave. Peut-être qu'on peut demander sur la liste de diffusion ?

**Comment by fabi1cazenave** [comment]
@JulioJu si tu as le temps, n’hésite pas. :-)

**Comment by fflorent** [comment]
up ?

**Comment by JulioJu** [comment]
@fflorent, @fabi1cazenave du coup pour demain ? ;-) ? Des news ? J'espère encore mais bon…

**Comment by LaetitiaAvrot** [comment]
A priori, ça coince quelque part. Comment puis je aider pour que cela se fasse ?

**Comment by JulioJu** [comment]
J'ai l'impression aussi :cry:. Si je peux aider aussi…

**Comment by fflorent** [comment]
@LaetitiaAvrot @JulioJu → https://twitter.com/tupperVim/status/1010248570417577985

Enjoy :)

**Comment by JulioJu** [comment]
I love :-) 

Therefore this issue is fixed :-). Thanks a lot !

**Comment by fabi1cazenave** [comment]
Je peux emmener en voiture les Grenoblois que ça intéresse. Faites-moi signe le cas échéant !
