### ISSUE TITLE
Lien "La Rache™" casse

### ISSUE THREAD

**Issue by jankeromnes** [tupperVim/tuppervim.github.io#18]
Le lien "La Rache™" pointe vers http://www.byatoo.com/la-rache/ qui ne fonctionne plus. Il semblerait que http://www.la-rache.com ne fonctionne plus non plus.

Pour remplacer, je suggere cette serie de diapositives sur SlideShare™ : http://www.slideshare.net/nobug/a1-rache

**Comment by maggick** [comment]
Effectivement.
On peut replacer le lien par celui des archives https://web.archive.org/web/20060813145615/http://www.la-rache.com/
@fabi1cazenave un avis ?

**Comment by jankeromnes** [comment]
Ah oui, excellent le lien vers les archives, je n'y avais pas pense.

**Comment by maggick** [comment]
est ce que je close l'issue du coup ?

**Comment by fabi1cazenave** [comment]
Oui, fermons.

**Comment by maggick** [comment]
Je ré-ouvre l'issue car quelqu'un a repris le site:
http://linuxfr.org/news/le-retour-de-la-methode-r-a-c-h-e

le site est maintenant sur github et est hébergé  sur une github page
https://github.com/la-rache/la-rache.com
http://www.la-rache.com/

**Comment by fabi1cazenave** [comment]
+1 pour rétablir le lien.
