### ISSUE TITLE
Problème de visualistion des archives

### ISSUE THREAD

**Issue by maggick** [tupperVim/tuppervim.github.io#203]
En cliquant sur un lien issue des archives (https://tuppervim.org/archives.html) comme par exemple https://tuppervim.org/archives/tuppervimatmozfr.org/2019-June Firefox propose de télécharger le fichier uniquement.
En le mettant en `.html`, l’affichage est relativement peu élégant.

**Comment by fabi1cazenave** [comment]
Alors déjà, merci d’avoir récupéré toutes ces archives ! :-)

Effectivement l’affichage pourrait être amélioré. Je vais tâcher de bricoler une moulinette pour mettre ces messages en HTML, avec le texte dans un `<pre>` et l’encodage qui va bien.

**Comment by fabi1cazenave** [comment]
Question bête, je présume qu’il n’y a aucun moyen pour un tel site (= github hp) de spécifier le type MIME de fichiers texte ?

Une alternative serait de passer tout le site en Jekyll / markdown, github gère ça très bien… mais c’est peut-être un poil overkill.

**Comment by maggick** [comment]
C'est overkill ;)

**Comment by maggick** [comment]
on peut envisager une solution en raw comme par exemple https://raw.githubusercontent.com/tupperVim/tuppervim.github.io/master/archives/tuppervimatmozfr.org/2012-April

**Comment by maggick** [comment]
(voir #205 )

**Comment by maggick** [comment]
Même problème avec le fichier `fortunes.md` https://tuppervim.org/fortunes.md

**Comment by maggick** [comment]
Framapad propose un export HTML qui n'est pas déconnant. Je propose de tester ça en ayant l'archive de septembre en doublon.

**Comment by maggick** [comment]
Avez vous un avis ?
https://tuppervim.org/archives/pads/paris-1909.html
vs
https://tuppervim.org/archives/pads/paris-1909

**Comment by Kleidukos** [comment]
:+1: pour le rendu HTML

**Comment by maggick** [comment]
sur une suggestion de Ool (irc) on peut juste rajouter une extension .txt au fichier d'archive:
https://tuppervim.org/archives/pads/paris-1909.html
vs
https://tuppervim.org/archives/pads/paris-1909.txt

**Comment by maggick** [comment]
Le fichier au format txt semble générer une 404. C'est étrange.

**Comment by maggick** [comment]
> Le fichier au format txt semble générer une 404. C'est étrange.

c'est fix.
