### ISSUE TITLE
Air Mozilla a changé, et l'URL de la vidéo des 5 ans avec

### ISSUE THREAD

**Issue by pandark** [tupperVim/tuppervim.github.io#211]
Une URL qui fonctionne : https://air.mozilla.org/event-redirect/293308/

Ça vaudrait peut-être le coup d'héberger la vidéo ailleurs…?

**Comment by maggick** [comment]
le lien https://air.mozilla.org/5-ans-de-tuppervim-a-paris-2017-04-04/ semble toujours fonctionner.

**Comment by pandark** [comment]
@maggick Je suis redirigé vers une page de login.

![Screenshot_2019-09-11 Mozilla Login](https://user-images.githubusercontent.com/271167/64677546-11203c00-d478-11e9-80e0-d561d8f37985.png)

**Comment by dmerejkowsky** [comment]
@pandark : tu peux essayer avec: https://air.mozilla.org/event-redirect/293308 ?
