### ISSUE TITLE
Le fichier pdf du cube vim n'est pas à jour par rapport au svg

### ISSUE THREAD

**Issue by carrieje** [tupperVim/tuppervim.github.io#64]
La commande pour sauter au paragraphe suivant sur le cube est fausse sur le cube pdf (`{` à la place de `}`).
Ce n'est pas le cas sur le svg.

**Comment by maggick** [comment]
est ce que le commit [05b7668c4fe747407ed524f23b68e9ad846ee5b9](https://github.com/tupperVim/tuppervim.github.io/commit/05b7668c4fe747407ed524f23b68e9ad846ee5b9) corrige le problème ?

**Comment by carrieje** [comment]
yep 👍

**Comment by fabi1cazenave** [comment]
Merci @carrieje, on ferme le ticket.

**Comment by maggick** [comment]
merci
